.. Global includes, substitutions, and common links.

.. |author_name| replace:: Yesudeep Mangalapilly
.. |author_email| replace:: yesudeep@gmail.com
.. |copyright| replace:: Copyright (C) 2011 Yesudeep Mangalapilly.
.. |project_name| replace:: ``pyoauth``
.. |project_version| replace:: 0.0.1

.. _issue tracker: http://github.com/gorakhargosh/pyoauth/issues
.. _code repository: http://github.com/gorakhargosh/pyoauth

