.. Global includes, substitutions, and common links.

.. |author_name| replace:: Yesudeep Mangalapilly
.. |author_email| replace:: yesudeep@gmail.com
.. |copyright| replace:: Copyright (C) 2011 Yesudeep Mangalapilly.
.. |project_name| replace:: ``pyoauth``
.. |project_version| replace:: 0.0.1

.. _issue tracker: http://github.com/gorakhargosh/pyoauth/issues
.. _code repository: http://github.com/gorakhargosh/pyoauth

.. _coverage: http://nedbatchelder.com/code/coverage/
.. _git: http://git-scm.org/
.. _github: http://github.com/
.. _nose: http://somethingaboutorange.com/mrl/projects/nose/0.11.2/
.. _pip: http://pypi.python.org/pypi/pip
.. _Python: http://python.org
.. _sphinx: http://sphinx.pocoo.org/
.. _zc.buildout: http://www.buildout.org/
